export const START_STUDENTS_FETCHING = 'START_STUDENTS_FETCHING';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const START_COURSES_FETCHING = 'START_COURSES_FETCHING';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';