export const COURSES_SUCCESS = 'COURSES_SUCCESS';
export const COURSES_START = 'COURSES_START';
export const COURSES_ERROR = 'COURSES_ERROR';
export const START_SUBSCRIBING = 'START_SUBSCRIBING';
export const SUBSCRIBE_ERROR = 'SUBSCRIBE_ERROR';
export const SUBSCRIPTION_SUCCESSFULL = 'SUBSCRIPTION_SUCCESSFULL';