export const PROFILE_START = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const START_FETCHING_USER_COURSES = 'START_FETCHING_USER_COURSES';
export const FETCHING_USER_COURSES_SUCCESS = 'FETCHING_USER_COURSES_SUCCESS';
export const USER_COURSES_ERROR = 'USER_COURSES_ERROR';
export const START_UPDATING = 'START_UPDATING';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';